window.people = [
  {
    "firstName": "Aleck",
    "lastName": "Landgraf",
    "image": "images/aleck.png",
    "role": "Software Engineer",
    "location": "Portland",
    "favoriteCostume": "Charlie Chaplin",
    "funFact": "My wife and I planned our wedding in six weeks.",
    "oneAirbnb": "https://one.airbnb.com/people/aleck_landgraf",
  },
  {
    "firstName": "Avand",
    "lastName": "Amiri",
    "image": "images/avand.png",
    "role": "Software Engineer, Frontend",
    "location": "San Francisco",
    "favoriteCostume": "Famous. I wore a black blazer, fedora, huge sunglasses, and  hired a couple college kids off Craigslist with flashy cameras to follow me around all night.",
    "funFact": "For the last 3 years, I’ve been teaching front-end web development at General Assembly part-time. If you ever want to learn some HTML, CSS, or JS, please come find me. I will hook you up!",
    "oneAirbnb": "https://one.airbnb.com/people/avand_amiri",
  },
  {
    "firstName": "Ben",
    "lastName": "Glenn",
    "image": "images/ben.png",
    "role": "Experience Researcher",
    "location": "San Francisco",
    "favoriteCostume": "Ostrich hunter",
    "funFact": "I took four years off to travel and to write about traveling. I’ve also climbed Mount Rainier four times.",
    "oneAirbnb": "https://one.airbnb.com/people/ben_glenn",
  },
  {
    "firstName": "Davi",
    "lastName": "Arnaut",
    "image": "images/davi.png",
    "role": "Software Engineer, Site Reliability",
    "location": "San Francisco",
    "favoriteCostume": "None",
    "funFact": "I can fly an airplane upside-down.",
    "oneAirbnb": "https://one.airbnb.com/people/davi_arnaut",
  },
  {
    "firstName": "Nizar",
    "lastName": "Hejazi",
    "image": "images/nizar.png",
    "role": "Software Engineer",
    "location": "Seattle",
    "favoriteCostume": "Gandalf the Grey",
    "funFact": "I can guess your age! :)",
    "oneAirbnb": "https://one.airbnb.com/people/nizar_hejazi",
  },
  {
    "firstName": "Jennifer",
    "lastName": "Yen",
    "image": "images/jennifer.png",
    "role": "Senior Brand Marketing Operations Manager Global",
    "location": "San Francisco",
    "favoriteCostume": "Dressing up as Disney’s Lilo and Stitch for Halloween with my son.",
    "funFact": "I love baking and buying sweets, but don’t particularly like eating sweets.",
    "oneAirbnb": "https://one.airbnb.com/people/jennifer_yen",
  },
  {
    "firstName": "John",
    "lastName": "Gargiulo",
    "image": "images/john.png",
    "role": "Product Marketing Manager",
    "location": "San Francisco",
    "favoriteCostume": "Disco Justin Timberlake",
    "funFact": "I’m a foodie. I opened sandwich restaurants in NYC but I don’t like sandwiches.",
    "oneAirbnb": "https://one.airbnb.com/people/john_gargiulo",
  },
  {
    "firstName": "Jo",
    "lastName": "Wai Lin",
    "image": "images/jo.png",
    "role": "Copywriter",
    "location": "San Francisco",
    "favoriteCostume": "Why is Halloween the only day we admit to wearing a mask?",
    "funFact": "If you have a picture with Winnie the Pooh at Disneyland in 2001, you might have a picture with me.",
    "oneAirbnb": "https://one.airbnb.com/people/josephine_wailin",
  },
  {
    "firstName": "Julio",
    "lastName": "Alvarez",
    "image": "images/julio.png",
    "role": "Product Marketing Manager",
    "location": "San Francisco",
    "favoriteCostume": "Who doesn’t like a good firefighter?",
    "funFact": "I can officiate weddings! In fact, just did my first one this year for my best friend, who started out as my Airbnb host.",
    "oneAirbnb": "https://one.airbnb.com/people/j_alvarez",
  },
  {
    "firstName": "Kaiyi",
    "lastName": "Li",
    "image": "images/kaiyi.png",
    "role": "Software Engineer, Product Security",
    "location": "San Francisco",
    "favoriteCostume": "Cowboy",
    "funFact": "In my childhood I lived in Monte Vista, Cape Town in South Africa. “Monte vista” means “moutain view” (Table Mountain) - coincidentally this is also the name of city I lived in when I first moved to the Bay Area.",
    "oneAirbnb": "https://one.airbnb.com/people/kaiyi_li",
  },
  {
    "firstName": "Keith",
    "lastName": "Ahn",
    "image": "images/keith.png",
    "role": "Experience Designer",
    "location": "San Francisco",
    "favoriteCostume": "Banana Horse",
    "funFact": "I can cry on demand.",
    "oneAirbnb": "https://one.airbnb.com/people/keith_ahn",
  },
  {
    "firstName": "Kyle",
    "lastName": "Bailey",
    "image": "images/kyle.png",
    "role": "Software Engineer, Full Stack/iOS",
    "location": "San Francisco",
    "favoriteCostume": "Obama + 2 Chainz = Two Termz",
    "funFact": "I haven’t watched TV in 5 years. So unfortunately, I haven’t seen that new cool show but I’m good at pretending that I have.",
    "oneAirbnb": "https://one.airbnb.com/people/kyle_bailey",
  },
  {
    "firstName": "Laura",
    "lastName": "Xu",
    "image": "images/laura.png",
    "role": "Software Engineer, Android",
    "location": "San Francisco",
    "favoriteCostume": "Jasmine (made it + Aladdin costume out of hot glue and won a DJI Phantom 3 drone at a costume contest)",
    "funFact": "I used to do Ballet Folklorico (Mexican folk dancing).",
    "oneAirbnb": "https://one.airbnb.com/people/laura_xu",
  },
  {
    "firstName": "Maeve",
    "lastName": "Gallagher",
    "image": "images/maeve.png",
    "role": "Community Organizer",
    "location": "Toronto",
    "favoriteCostume": "Sailor Moon",
    "funFact": "I love jumping from high places -- most recently the highest bungee jump in Canada.",
    "oneAirbnb": "https://one.airbnb.com/people/maeve_gallagher",
  },
  {
    "firstName": "Jay",
    "lastName": "Jayakumaran",
    "image": "images/jay.png",
    "role": "CRM Solution Architect",
    "location": "San Francisco",
    "favoriteCostume": "Cop dress for a fancy dress competition in high school",
    "funFact": "I had special interests to try Culinary school and medical school for a while; finally, I decied to do Engineering and pursued Software Engineering.",
    "oneAirbnb": "https://one.airbnb.com/people/sadeesh_jayakumaran",
  },
  {
    "firstName": "Sahil",
    "lastName": "Shah",
    "image": "images/sahil.png",
    "role": "Software Engineer",
    "location": "San Francisco",
    "favoriteCostume": "Made a vest and hat out of Trader Joe’s bags, I was Trader Joe.",
    "funFact": "I have a MASSIVE sweet tooth, but I don’t like chocolate.",
    "oneAirbnb": "https://one.airbnb.com/people/sahil_shah",
  },
  {
    "firstName": "Sonia",
    "lastName": "Giddens",
    "image": "images/sonia.png",
    "role": "Relationship Manager, Business Travel",
    "location": "San Francisco",
    "favoriteCostume": "Swine Flu (picture two people dressed in all pink, pig ears and snout; one wearing a shirt with “H1” and the other with “N1”)",
    "funFact": "I got married in a roller rink on roller skates wearing a retro 70’s gogo dress.",
    "oneAirbnb": "https://one.airbnb.com/people/sonia_giddens",
  },
  {
    "firstName": "Sophia",
    "lastName": "Sun",
    "image": "images/sophia.png",
    "role": "Data Scientist Growth, Onboarding",
    "location": "San Francisco",
    "favoriteCostume": "Arale",
    "funFact": "I have tried >50 kinds of seafood so far. The number is still counting.",
    "oneAirbnb": "https://one.airbnb.com/people/sophia_sun",
  },
  {
    "firstName": "Stefan",
    "lastName": "Novak",
    "image": "images/stefan.png",
    "role": "Software Engineer",
    "location": "Portland",
    "favoriteCostume": "The Invisible Pedestrian (an homage to Dan Aykroyd on SNL)",
    "funFact": "I used to work on designing satellite missions for NASA. When I say that working is here out of this world, I mean it!",
    "oneAirbnb": "https://one.airbnb.com/people/stefan_novak",
  },
  {
    "firstName": "Yutian",
    "lastName": "Liu",
    "image": "images/yutian.png",
    "role": "Software Engineer, iOS",
    "location": "San Francisco",
    "favoriteCostume": "Wizzard",
    "funFact": "My mother language is Cantonese but my mother cannot speak Cantonese.",
    "oneAirbnb": "https://one.airbnb.com/people/yutian_liu",
  },
  {
    "firstName": "Zhentao",
    "lastName": "Sun",
    "image": "images/zhentao.png",
    "role": "Software Engineer",
    "location": "San Francisco",
    "favoriteCostume": "James Bond",
    "funFact": "I have more than 15 TV set top box or stick though I don’t watch TV that much.",
    "oneAirbnb": "https://one.airbnb.com/people/zhentao_sun",
  }
];
